---

#- hosts: ansible_host
#  become: true
#  gather_facts: true
#  roles:
#    - role: setup_terraform_binaries

- hosts: ansible_host
  become: true
  gather_facts: false
  roles:
    - role: vm_provisioning_vault_via_ansible

- hosts: k8s
  become: true
  gather_facts: false
  roles:
    - role: setup_vault
