---
- name: download jira software v8.6.1 linux x64 binary
  get_url:
    url: "https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-8.6.1-x64.bin"
    dest: /tmp
    mode: "0700"

#- name: run jira binary with pre-answered prompts
#  expect:
#    command: /tmp/atlassian-jira-software-8.6.1-x64.bin
