---
- name: download confluence v7.2.1 linux x64 binary
  get_url:
    url: "https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.2.1-x64.bin"
    dest: /tmp
    mode: "0700"
